---

- hosts: nodess
  tasks:
   - name: install apache2
     become: true
     package:
      name: httpd*
      state: present
 
   - name: restart service
     become: true
     service:
      name: httpd
      state: restarted
        
      
